In [1]:
import pandas as pd
import numpy as np
import mxnet as mx
from mxnet import nd, autograd, gluon, init
from mxnet.gluon import nn, rnn
import gluonnlp as nlp
import pkuseg
import multiprocessing as mp
import time
from d2l import try_gpu
import itertools
import jieba
from sklearn.metrics import accuracy_score, f1_score
# fixed random number seed
np.random.seed(9102)
mx.random.seed(9102)

/home/user_data/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
DATA_FOLDER = 'data/'
TRAIN_DATA = 'train.csv'
WORD_EMBED = 'sgns.weibo.word'
LABEL_FILE = 'train.label'
N_ROWS=10000
ctx = mx.gpu(1)
seg = pkuseg.pkuseg(model_name='web')
ctx

gpu(1)

In [6]:
train_df = pd.read_csv(DATA_FOLDER+TRAIN_DATA, sep='|')
train_df = train_df.sample(frac=1)

In [7]:
dataset =[ [row[0], row[1]] for _, row in train_df.iterrows()]
train_dataset, valid_dataset = nlp.data.train_valid_split(dataset, .1)
len(train_dataset), len(valid_dataset)

(776847, 86317)

In [5]:
def tokenizer(x):
    tweet, label = x
    if type(tweet) != str:
        tweet = str(tweet)
    word_list = seg.cut(tweet)
    return word_list, label

def get_length(x):
    return float(len(x[0]))

def to_word_list(dataset):
    start = time.time()
    with mp.Pool() as pool:
        # Each sample is processed in an asynchronous manner.
        dataset = gluon.data.ArrayDataset(pool.map(tokenizer, dataset))
        lengths = gluon.data.ArrayDataset(pool.map(get_length, dataset))
    end = time.time()

    print('Done! Tokenizing Time={:.2f}s, #Sentences={}'.format(end - start, len(dataset)))
    return dataset, lengths

train_word_list, train_word_lengths = to_word_list(train_dataset)
valid_word_list, valid_word_lengths = to_word_list(valid_dataset)

Done! Tokenizing Time=62.54s, #Sentences=776847
Done! Tokenizing Time=7.20s, #Sentences=86317


In [6]:
train_seqs = [sample[0] for sample in train_word_list]
counter = nlp.data.count_tokens(list(itertools.chain.from_iterable(train_seqs)))

vocab = nlp.Vocab(counter, max_size=200000)

# load customed pre-trained embedding
embedding_weights = nlp.embedding.TokenEmbedding.from_file(file_path=DATA_FOLDER+WORD_EMBED)
vocab.set_embedding(embedding_weights)
print(vocab)

def token_to_idx(x):
    return vocab[x[0]], x[1]

# A token index or a list of token indices is returned according to the vocabulary.
with mp.Pool() as pool:
    train_dataset = pool.map(token_to_idx, train_word_list)
    valid_dataset = pool.map(token_to_idx, valid_word_list)

/home/wup/.local/lib/python3.6/site-packages/gluonnlp/embedding/token_embedding.py:296: UserWarning: line 0 in data/sgns.weibo.bigram-char: skipped likely header line.
  .format(line_num, pretrained_file_path))


Vocab(size=200004, unk="<unk>", reserved="['<pad>', '<bos>', '<eos>']")


In [7]:
batch_size = 64
bucket_num = 10
bucket_ratio = 0.5


def get_dataloader():
    # Construct the DataLoader Pad data, stack label and lengths
    batchify_fn = nlp.data.batchify.Tuple(nlp.data.batchify.Pad(axis=0), \
                                          nlp.data.batchify.Stack())

    # in this example, we use a FixedBucketSampler,
    # which assigns each data sample to a fixed bucket based on its length.
    batch_sampler = nlp.data.sampler.FixedBucketSampler(
        train_word_lengths,
        batch_size=batch_size,
        num_buckets=bucket_num,
        ratio=bucket_ratio,
        shuffle=True)
    print(batch_sampler.stats())

    # train_dataloader
    train_dataloader = gluon.data.DataLoader(
        dataset=train_dataset,
        batch_sampler=batch_sampler,
        batchify_fn=batchify_fn)
    # valid_dataloader
    valid_dataloader = gluon.data.DataLoader(
        dataset=valid_dataset,
        batch_size=batch_size,
        shuffle=False,
        batchify_fn=batchify_fn)
    return train_dataloader, valid_dataloader

train_dataloader, valid_dataloader = get_dataloader()

FixedBucketSampler:
  sample_num=776847, batch_num=4617
  key=[22, 35, 48, 61, 74, 87, 100, 113, 126, 139]
  cnt=[637662, 69980, 31150, 17042, 11028, 7082, 2748, 149, 3, 3]
  batch_size=[202, 127, 92, 72, 64, 64, 64, 64, 64, 64]


In [8]:
for tweet, label in train_dataloader:
    print(tweet, label)
    break


[[0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [4.9000e+02 5.0000e+00 1.4615e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.5000e+01 9.2900e+02 5.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [6.3300e+02 5.1000e+01 3.2100e+02 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [3.2600e+02 1.6300e+03 1.1996e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0500e+02 4.2000e+01 1.4000e+01 ... 0.0000e+00 0.0000e+00 0.0000e+00]]
<NDArray 202x22 @cpu_shared(0)> 
[34 18 10 15  3 29 31 30 17  3 14  1 34 42 27 28 27 34 14 29 34 34 23 14
 31 12 34 35 13 29 31 12 40 19 42 29 16  3 50 34 70  6 19 14 27 35 17 12
 35 60 15 41 39 12 61 58 70 22 31 23  9 23 24  6 14 20 12  1 29 40 15 43
 55 15 31  3  1  3 29 17  3 37 14 16 29 13 12 47 30  3  3 62 36 33 35 10
 52 29 12  1 14 33  3  3  3 12 16 15 14 16 29 15 31 60  3 31 59  3 19 34
 53 27 35 23 19 35 40 35 25 52 34 27 70 60 27  9 70 52 10 35 18 34 12 22
 31 34 50  3 16  3 17 14 32 34 31 52 34  3 29 38  3  3  3 28 24 70 14 14
 37 29 35 1

## Model contruction
Self attention layer, weighted cross entropy, and whole model

In [9]:
# custom attention layer
# in this class, we want to implement the operation:
# softmax(W_2 * tanh(W_1 * H))
# where H is the word embedding of the whole sentence, of shape (num_of_word, embed_size)
class SelfAttention(nn.HybridBlock):
    def __init__(self, att_unit, att_hops, **kwargs):
        super(SelfAttention, self).__init__(**kwargs)
        with self.name_scope():
            # this layer is tanh(w_1 * H), the att_unit corresponds to d_a in the essay
            self.ut_dense = nn.Dense(att_unit, activation='relu', flatten=False)
            # this layer implements the multiple hops
            self.et_dense = nn.Dense(att_hops, activation=None, flatten=False)

    def hybrid_forward(self, F, x): # F is the backend which implements the tensor operation
        # x shape: [batch_size, seq_len, embedding_width]
        # ut shape: [batch_size, seq_len, att_unit]
        ut = self.ut_dense(x) # batch_size * seq_len [* embed_size * embed_size *] att_unit
        # et shape: [batch_size, seq_len, att_hops]
        et = self.et_dense(ut)# batch_size * seq_len [* att_unit * att_unit *] att_hops

        # att shape: [batch_size,  att_hops, seq_len]
        # softmax is performed along the seq_len dimension
        att = F.softmax(F.transpose(et, axes=(0, 2, 1)), axis=-1)
        # output shape [batch_size, att_hops, embedding_width]
        output = F.batch_dot(att, x)
        # output is the weighted matrix representation of the matrix
        # att is the weighted vector we use as attention
        return output, att
    
# d_a = 20, hops = 5
print(SelfAttention(20, 5))

SelfAttention(
  (ut_dense): Dense(None -> 20, Activation(relu))
  (et_dense): Dense(None -> 5, linear)
)


In [10]:
class WeightedSoftmaxCE(nn.HybridBlock):
    def __init__(self, sparse_label=True, from_logits=False,  **kwargs):
        super(WeightedSoftmaxCE, self).__init__(**kwargs)
        with self.name_scope():
            self.sparse_label = sparse_label
            self.from_logits = from_logits

    def hybrid_forward(self, F, pred, label, class_weight, depth=None):
        if self.sparse_label:
            label = F.reshape(label, shape=(-1, ))
            label = F.one_hot(label, depth)
        if not self.from_logits:
            pred = F.log_softmax(pred, -1)

        weight_label = F.broadcast_mul(label, class_weight)
        loss = -F.sum(pred * weight_label, axis=-1)

        # return F.mean(loss, axis=0, exclude=True)
        return loss

In [11]:
class SelfAttentiveBiLSTM(nn.HybridBlock):
    def __init__(self, vocab_len, embsize, nhidden, nlayers, natt_unit, natt_hops, \
                 nfc, nclass, # these two params are not used currrently
                 drop_prob, pool_way, prune_p=None, prune_q=None, **kwargs):
        super(SelfAttentiveBiLSTM, self).__init__(**kwargs)
        with self.name_scope():
            # now we switch back to shared layers
            self.embedding_layer = nn.Embedding(vocab_len, embsize)
            
            self.bilstm = rnn.LSTM(nhidden, num_layers=nlayers, dropout=drop_prob, \
                                   bidirectional=True)
            
            self.att_encoder = SelfAttention(natt_unit, natt_hops)
            self.dense = nn.Dense(nfc, activation='relu')
            # this layer is used to output the final class
            self.output_layer = nn.Dense(nclass)
            
            self.dense_p, self.dense_q = None, None
            if all([prune_p, prune_q]):
                self.dense_p = nn.Dense(prune_p, activation='relu', flatten=False)
                self.dense_q = nn.Dense(prune_q, activation='relu', flatten=False)

            self.drop_prob = drop_prob
            self.pool_way = pool_way

    def hybrid_forward(self, F, inp):
        # inp_embed size: [batch, seq_len, embed_size]
        inp_embed = self.embedding_layer(inp)
        # rnn requires the first dimension to be the time steps
        h_output = self.bilstm(F.transpose(inp_embed, axes=(1, 0, 2)))
        # att_output: [batch, att_hops, emsize]
        output, att = self.att_encoder(F.transpose(h_output, axes=(1, 0, 2)))
        '''
        FIXME: now this code will only work with flatten
        '''
        dense_input = None
        if self.pool_way == 'flatten':
            dense_input = F.Dropout(F.flatten(output), self.drop_prob)
        else:
            raise NotImplemented
        '''
        elif self.pool_way == 'mean':
            dense_input = F.Dropout(F.mean(att_output, axis=1), self.drop_prob)
        elif self.pool_way == 'prune' and all([self.dense_p, self.dense_q]):
            # p_section: [batch, att_hops, prune_p]
            p_section = self.dense_p(att_output)
            # q_section: [batch, emsize, prune_q]
            q_section = self.dense_q(F.transpose(att_output, axes=(0, 2, 1)))
            dense_input = F.Dropout(F.concat(F.flatten(p_section), F.flatten(q_section), dim=-1), self.drop_prob)
        '''
        dense_out = self.dense(dense_input)
        output = self.output_layer(F.Dropout(dense_out, self.drop_prob))

        return output, att

In [21]:
vocab_len = len(vocab)
emsize = 300   # word embedding size
nhidden = 200    # lstm hidden_dim
nlayers = 1     # lstm layers
natt_unit = 200     # the hidden_units of attention layer
natt_hops = 10    # the channels of attention
nfc = 128  # last dense layer size
nclass = 72 # we have 72 emoji in total

drop_prob = 0.
pool_way = 'flatten'    # # The way to handle M
prune_p = None
prune_q = None


try:
    assert(False)
    model = gluon.nn.SymbolBlock.imports("model/model-symbol.json", ['data'], \
                                         "model/model-0001.params", ctx=ctx)
    print('use saved model params to start')
except:
    model = SelfAttentiveBiLSTM(vocab_len, emsize, nhidden, nlayers,
                            natt_unit, natt_hops, nfc, nclass,
                            drop_prob, pool_way, prune_p, prune_q)

    print('initialize a new model')
    model.initialize(init=init.Xavier(), ctx=ctx)
    model.hybridize()

    # Attach a pre-trained glove word vector to the embedding layer
    model.embedding_layer.weight.set_data(vocab.embedding.idx_to_vec)
    # fixed the embedding layer
    model.embedding_layer.collect_params().setattr('grad_req', 'null')

print(ctx, model)

initialize a new model
gpu(1) SelfAttentiveBiLSTM(
  (embedding_layer): Embedding(200004 -> 300, float32)
  (bilstm): GRU(None -> 200, TNC, bidirectional)
  (att_encoder): SelfAttention(
    (ut_dense): Dense(None -> 200, Activation(relu))
    (et_dense): Dense(None -> 10, linear)
  )
  (dense): Dense(None -> 128, Activation(relu))
  (output_layer): Dense(None -> 72, linear)
)


In [13]:
vocab.embedding.idx_to_vec[vocab.embedding.token_to_idx['i']]


[-0.216152  0.111755  0.131167  0.108303 -0.56618   0.154915 -0.682917
  0.184372 -1.259019 -0.270754 -0.295431 -0.477648  0.313637 -0.249563
  0.464083 -0.177201  0.250866  0.63421  -0.023141 -0.083413 -0.086886
  0.373867 -0.120577  0.154108  0.075599  0.749676  0.064633  0.346573
 -0.375857  0.170967 -0.387877  0.621435  0.252638 -0.327384  0.03449
  0.59719   0.396766  0.550666 -0.658407 -0.525238  0.167532 -0.511287
 -0.360124 -0.815612 -0.511149 -0.866398  0.068793 -0.629899  0.036555
 -0.245903 -0.501821  0.222177 -0.887551 -0.059061  0.357666  0.444045
 -0.632446  0.706885  0.488229  0.459782  0.109316 -0.090775 -0.408769
  0.25539   0.630114 -0.136657 -0.541437  0.510262 -0.273591  0.137092
 -0.586211 -0.199848  0.066356  0.603941 -0.288794 -0.023497 -0.258354
  0.341849  0.427584 -0.001543  0.755926  0.718712 -1.017008  0.452808
  0.173271  0.29188   0.644698  0.49299   0.216398  0.517657  0.00933
  0.858918 -0.384057 -0.178975 -0.281533  1.395328  0.856061  0.560499
 -0.335

## Training helpers
Calculate loss, one epoch computation and top function for train and valid

In [22]:
def calculate_loss(x, y, model, loss, class_weight, penal_coeff):
    pred, att = model(x)
    y = nd.array(y.asnumpy().astype('int32')).as_in_context(ctx)
    if loss_name in ['sce', 'l1', 'l2']:
        l = loss(pred, y)
    elif loss_name == 'wsce':
        l = loss(pred, y, class_weight, class_weight.shape[0])
    else:
        raise NotImplemented
    # penalty, now we have two att's
    diversity_penalty = nd.batch_dot(att, nd.transpose(att, axes=(0, 2, 1))) - \
                        nd.eye(att.shape[1], ctx=att.context)
    l = l + penal_coeff * diversity_penalty.norm(axis=(1, 2))

    return pred, l

In [23]:
def one_epoch(data_iter, model, loss, trainer, ctx, is_train, epoch,
              penal_coeff=0.0, clip=None, class_weight=None, loss_name='sce'):

    loss_val = 0.
    total_pred = []
    total_true = []
    n_batch = 0

    for batch_x, batch_y in data_iter:
        batch_x = batch_x.as_in_context(ctx)
        batch_y = batch_y.as_in_context(ctx)

        if is_train:
            with autograd.record():
                batch_pred, l = calculate_loss(batch_x, batch_y, model, \
                                               loss, class_weight, penal_coeff)

            # backward calculate
            l.backward()

            # clip gradient
            clip_params = [p.data() for p in model.collect_params().values()]
            if clip is not None:
                norm = nd.array([0.0], ctx)
                for param in clip_params:
                    if param.grad is not None:
                        norm += (param.grad ** 2).sum()
                norm = norm.sqrt().asscalar()
                if norm > clip:
                    for param in clip_params:
                        if param.grad is not None:
                            param.grad[:] *= clip / norm

            # update parmas
            trainer.step(batch_x.shape[0])

        else:
            batch_pred, l = calculate_loss(batch_x, batch_y, model, \
                                           loss, class_weight, penal_coeff)

        # keep result for metric
        batch_pred = nd.argmax(nd.softmax(batch_pred, axis=1), axis=1).asnumpy()
        batch_true = np.reshape(batch_y.asnumpy(), (-1, ))
        total_pred.extend(batch_pred.tolist())
        total_true.extend(batch_true.tolist())
        
        batch_loss = l.mean().asscalar()

        n_batch += 1
        loss_val += batch_loss

        # check the result of traing phase
        if is_train and n_batch % 400 == 0:
            print('epoch %d, batch %d, batch_train_loss %.4f, batch_train_acc %.3f' %
                  (epoch, n_batch, batch_loss, accuracy_score(batch_true, batch_pred)))

    # metric
    F1 = f1_score(np.array(total_true), np.array(total_pred), average='weighted')
    acc = accuracy_score(np.array(total_true), np.array(total_pred))
    loss_val /= n_batch

    if is_train:
        print('epoch %d, learning_rate %.5f \n\t train_loss %.4f, acc_train %.3f, F1_train %.3f, ' %
              (epoch, trainer.learning_rate, loss_val, acc, F1))
        # declay lr
        if epoch % 3 == 0:
            trainer.set_learning_rate(trainer.learning_rate * 0.9)
    else:
        print('\t valid_loss %.4f, acc_valid %.3f, F1_valid %.3f, ' % (loss_val, acc, F1))

In [24]:
def train_valid(data_iter_train, data_iter_valid, model, loss, trainer, ctx, nepochs,
                penal_coeff=0.0, clip=None, class_weight=None, loss_name='sce'):

    for epoch in range(1, nepochs+1):
        start = time.time()
        # train
        is_train = True
        one_epoch(data_iter_train, model, loss, trainer, ctx, is_train,
                  epoch, penal_coeff, clip, class_weight, loss_name)

        # valid
        is_train = False
        one_epoch(data_iter_valid, model, loss, trainer, ctx, is_train,
                  epoch, penal_coeff, clip, class_weight, loss_name)
        end = time.time()
        print('time %.2f sec' % (end-start))
        print("*"*100)

## Train
Now we will train this model. To handle data inbalance, we first set an estimated weight of the labels.

In [25]:
from util import get_weight
weight_list = get_weight(DATA_FOLDER, LABEL_FILE)
# print(weight_list)
class_weight = None
loss_name = 'sce'
optim = 'adam'
lr = 0.001
penal_coeff = 0.0003
clip = .5
nepochs = 5

trainer = gluon.Trainer(model.collect_params(), optim, {'learning_rate': lr})

if loss_name == 'sce':
    loss = gluon.loss.SoftmaxCrossEntropyLoss()
elif loss_name == 'wsce':
    loss = WeightedSoftmaxCE()
    # the value of class_weight is obtained by counting data in advance. It can be seen as a hyperparameter.
    class_weight = nd.array(weight_list, ctx=ctx)
elif loss_name == 'l1':
    loss = gluon.loss.L1Loss()
elif loss_name == 'l2':
    loss = gluon.loss.L2Loss()

In [26]:
# train and valid
print(ctx)
train_valid(train_dataloader, valid_dataloader, model, loss, \
            trainer, ctx, nepochs, penal_coeff=penal_coeff, \
            clip=clip, class_weight=class_weight, loss_name=loss_name)

gpu(1)
epoch 1, batch 400, batch_train_loss 3.5288, batch_train_acc 0.181
epoch 1, batch 800, batch_train_loss 3.4437, batch_train_acc 0.213
epoch 1, batch 1200, batch_train_loss 3.4180, batch_train_acc 0.193
epoch 1, batch 1600, batch_train_loss 3.3982, batch_train_acc 0.158
epoch 1, batch 2000, batch_train_loss 3.4827, batch_train_acc 0.129
epoch 1, batch 2400, batch_train_loss 3.5532, batch_train_acc 0.158
epoch 1, batch 2800, batch_train_loss 3.4652, batch_train_acc 0.163
epoch 1, batch 3200, batch_train_loss 3.4479, batch_train_acc 0.124
epoch 1, batch 3600, batch_train_loss 3.4505, batch_train_acc 0.158
epoch 1, batch 4000, batch_train_loss 3.2319, batch_train_acc 0.213
epoch 1, batch 4400, batch_train_loss 3.1403, batch_train_acc 0.196


/home/wup/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


epoch 1, learning_rate 0.00100 
	 train_loss 3.4646, acc_train 0.162, F1_train 0.047, 
	 valid_loss 3.4134, acc_valid 0.169, F1_valid 0.051, 
time 96.43 sec
****************************************************************************************************
epoch 2, batch 400, batch_train_loss 3.2242, batch_train_acc 0.168
epoch 2, batch 800, batch_train_loss 3.3861, batch_train_acc 0.196
epoch 2, batch 1200, batch_train_loss 3.2675, batch_train_acc 0.183
epoch 2, batch 1600, batch_train_loss 3.0853, batch_train_acc 0.217
epoch 2, batch 2000, batch_train_loss 3.3806, batch_train_acc 0.217
epoch 2, batch 2400, batch_train_loss 3.4099, batch_train_acc 0.153
epoch 2, batch 2800, batch_train_loss 3.4599, batch_train_acc 0.158
epoch 2, batch 3200, batch_train_loss 3.4904, batch_train_acc 0.173
epoch 2, batch 3600, batch_train_loss 3.2755, batch_train_acc 0.205
epoch 2, batch 4000, batch_train_loss 3.3430, batch_train_acc 0.203
epoch 2, batch 4400, batch_train_loss 3.3066, batch_train_acc 0.

In [8]:
model.export("model/self-att-179", epoch=1)

NameError: name 'model' is not defined

In [65]:
TEST_DATA = 'test.csv'
test_df = pd.read_csv(DATA_FOLDER+TEST_DATA, header=None, sep='\t')

model = gluon.nn.SymbolBlock.imports("model/self-att-207-symbol.json", ['data'], \
                                     "model/self-att-207-0001.params", ctx=ctx)

In [69]:
predictions = []
start = time.time()
for _, tweet in test_df.iterrows():
    token = vocab[seg.cut(tweet[1])]
    if len(token)==0:
        token = [0.]
    inp = nd.array(token, ctx=ctx).reshape(1,-1)
    pred, _ = model(inp)
    pred = nd.argmax(pred, axis=1).asscalar()
    predictions.append(int(pred))
    if len(predictions)%2000==0:
        ckpt = time.time()
        print('current pred len %d, time %.2fs' % (len(predictions), ckpt-start))
        start = ckpt
submit = pd.DataFrame({'Expected': predictions})
submit.to_csv('submission.csv', sep=',', index_label='ID')

current pred len 2000, time 9.44s
current pred len 4000, time 9.23s
current pred len 6000, time 9.37s
current pred len 8000, time 9.25s
current pred len 10000, time 9.29s
current pred len 12000, time 7.66s
current pred len 14000, time 6.21s
current pred len 16000, time 8.77s
current pred len 18000, time 9.16s
current pred len 20000, time 8.67s
current pred len 22000, time 9.03s
current pred len 24000, time 9.26s
current pred len 26000, time 9.28s
current pred len 28000, time 8.79s
current pred len 30000, time 9.34s
current pred len 32000, time 9.34s
current pred len 34000, time 9.42s
current pred len 36000, time 9.38s
current pred len 38000, time 9.30s
current pred len 40000, time 9.38s
current pred len 42000, time 9.17s
current pred len 44000, time 9.31s
current pred len 46000, time 9.31s
current pred len 48000, time 9.22s
current pred len 50000, time 9.25s
current pred len 52000, time 9.16s
current pred len 54000, time 9.40s
current pred len 56000, time 9.21s
current pred len 58000, 